Remove cache again
Looking to fix the following error:
```
Error: [Errno 2] No such file or directory: '/home/circleci/mignonnesaurus-blog/venv/bin/python'

Exited with code exit status 1

CircleCI received exit code 1
```

We will need to find a new method to do this, perhaps using pipenv.