Fix Firefox installation issue in the CircleCI build (#466)
Fixes the following error in the CircleCI build:

```
XPCOMGlueLoad error for file /usr/local/bin/firefox-91.0.2/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
Something went wrong; the specified version of Firefox could not be installed

Exited with code exit status 1

CircleCI received exit code 1
```

And it does so by using the new next-gen Convenience Images from CircleCI.

Also, had to remove the dependencies cache due to the following error:
```
Error: [Errno 2] No such file or directory: '/home/circleci/mignonnesaurus-blog/venv/bin/python'

Exited with code exit status 1

CircleCI received exit code 1
```

We will need to find a new method to use a dependencies (requirements) cache in the builds, perhaps it's time to migrate to Pipenv :)